// AUTOGENERATED - MANUAL CHANGES WILL BE REVERTED BY THE GENERATOR
// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0;

// WIP: written by hand with placeholder addresses (0x...10XX) until the Sentora market is deployed
import {IHub, IHubConfigurator, ISpoke, ISpokeConfigurator, ITokenizationSpoke, ITreasurySpoke, IAaveOracle, IConfigPositionManager, IGiverPositionManager, ITakerPositionManager, INativeTokenGateway, ISignatureGateway, IAaveV4ConfigEngine, IAccessManagerEnumerable, IBasicInterestRateStrategy, PositionManagers} from './AaveV4.sol';
library AaveV4EthereumSentora {
  // https://etherscan.io/address/0x0000000000000000000000000000000000001001
  IAccessManagerEnumerable internal constant ACCESS_MANAGER =
    IAccessManagerEnumerable(0x0000000000000000000000000000000000001001);

  // https://etherscan.io/address/0x0000000000000000000000000000000000001002
  IHubConfigurator internal constant HUB_CONFIGURATOR =
    IHubConfigurator(0x0000000000000000000000000000000000001002);

  // https://etherscan.io/address/0x0000000000000000000000000000000000001003
  ISpokeConfigurator internal constant SPOKE_CONFIGURATOR =
    ISpokeConfigurator(0x0000000000000000000000000000000000001003);

  // https://etherscan.io/address/0x0000000000000000000000000000000000001004
  ITreasurySpoke internal constant TREASURY_SPOKE =
    ITreasurySpoke(0x0000000000000000000000000000000000001004);

  // https://etherscan.io/address/0xa1673fbD457747A05e91D9ef904Cb12827916B1E
  IAaveV4ConfigEngine internal constant CONFIG_ENGINE =
    IAaveV4ConfigEngine(0xa1673fbD457747A05e91D9ef904Cb12827916B1E);

  // https://etherscan.io/address/0x0000000000000000000000000000000000001005
  address internal constant RISK_STEWARD = 0x0000000000000000000000000000000000001005;

  // https://etherscan.io/address/0x0000000000000000000000000000000000001006
  address internal constant PERMISSIONED_PAYLOADS_CONTROLLER =
    0x0000000000000000000000000000000000001006;

  // https://etherscan.io/address/0x0000000000000000000000000000000000001007
  address internal constant PERMISSIONED_PAYLOADS_CONTROLLER_EXECUTOR =
    0x0000000000000000000000000000000000001007;
}
library AaveV4EthereumSentoraHubs {
  // https://etherscan.io/address/0x0000000000000000000000000000000000001010
  IHub internal constant SENTORA_HUB = IHub(0x0000000000000000000000000000000000001010);
}
library AaveV4EthereumSentoraSpokes {
  // https://etherscan.io/address/0x0000000000000000000000000000000000001004
  ITreasurySpoke internal constant TREASURY_SPOKE =
    ITreasurySpoke(0x0000000000000000000000000000000000001004);

  // https://etherscan.io/address/0x0000000000000000000000000000000000001011
  ISpoke internal constant RLUSD_YIELD_SPOKE = ISpoke(0x0000000000000000000000000000000000001011);

  // https://etherscan.io/address/0x0000000000000000000000000000000000001014
  IAaveOracle internal constant RLUSD_YIELD_SPOKE_ORACLE =
    IAaveOracle(0x0000000000000000000000000000000000001014);

  // https://etherscan.io/address/0x0000000000000000000000000000000000001012
  ISpoke internal constant OUSD_YIELD_SPOKE = ISpoke(0x0000000000000000000000000000000000001012);

  // https://etherscan.io/address/0x0000000000000000000000000000000000001015
  IAaveOracle internal constant OUSD_YIELD_SPOKE_ORACLE =
    IAaveOracle(0x0000000000000000000000000000000000001015);

  // https://etherscan.io/address/0x0000000000000000000000000000000000001013
  ISpoke internal constant BLUECHIP_SPOKE = ISpoke(0x0000000000000000000000000000000000001013);

  // https://etherscan.io/address/0x0000000000000000000000000000000000001016
  IAaveOracle internal constant BLUECHIP_SPOKE_ORACLE =
    IAaveOracle(0x0000000000000000000000000000000000001016);
}
library AaveV4EthereumSentoraPositionManagers {
  // https://etherscan.io/address/0x0000000000000000000000000000000000001017
  IGiverPositionManager internal constant GIVER_POSITION_MANAGER =
    IGiverPositionManager(0x0000000000000000000000000000000000001017);

  // https://etherscan.io/address/0x0000000000000000000000000000000000001018
  ITakerPositionManager internal constant TAKER_POSITION_MANAGER =
    ITakerPositionManager(0x0000000000000000000000000000000000001018);

  // https://etherscan.io/address/0x0000000000000000000000000000000000001019
  IConfigPositionManager internal constant CONFIG_POSITION_MANAGER =
    IConfigPositionManager(0x0000000000000000000000000000000000001019);

  // https://etherscan.io/address/0x0000000000000000000000000000000000001020
  INativeTokenGateway internal constant NATIVE_TOKEN_GATEWAY =
    INativeTokenGateway(0x0000000000000000000000000000000000001020);

  // https://etherscan.io/address/0x0000000000000000000000000000000000001021
  ISignatureGateway internal constant SIGNATURE_GATEWAY =
    ISignatureGateway(0x0000000000000000000000000000000000001021);
}
library AaveV4EthereumSentoraExternalLibraries {
  // https://etherscan.io/address/0x88dF535473C5adf1f57789734A05E555F7Deb8DB
  address internal constant LIQUIDATION_LOGIC = 0x88dF535473C5adf1f57789734A05E555F7Deb8DB;
}
library AaveV4EthereumSentoraGetters {
  function getAllHubs() internal pure returns (IHub[] memory) {
    IHub[] memory hubs = new IHub[](1);
    hubs[0] = AaveV4EthereumSentoraHubs.SENTORA_HUB;
    return hubs;
  }

  function getAllSpokes() internal pure returns (ISpoke[] memory) {
    ISpoke[] memory spokes = new ISpoke[](3);
    spokes[0] = AaveV4EthereumSentoraSpokes.RLUSD_YIELD_SPOKE;
    spokes[1] = AaveV4EthereumSentoraSpokes.OUSD_YIELD_SPOKE;
    spokes[2] = AaveV4EthereumSentoraSpokes.BLUECHIP_SPOKE;
    return spokes;
  }

  function getAllSpokesRaw() internal pure returns (address[] memory) {
    address[] memory spokes = new address[](4);
    spokes[0] = address(AaveV4EthereumSentoraSpokes.TREASURY_SPOKE);
    spokes[1] = address(AaveV4EthereumSentoraSpokes.RLUSD_YIELD_SPOKE);
    spokes[2] = address(AaveV4EthereumSentoraSpokes.OUSD_YIELD_SPOKE);
    spokes[3] = address(AaveV4EthereumSentoraSpokes.BLUECHIP_SPOKE);
    return spokes;
  }

  function getPositionManagers() internal pure returns (PositionManagers memory) {
    return
      PositionManagers({
        giver: AaveV4EthereumSentoraPositionManagers.GIVER_POSITION_MANAGER,
        taker: AaveV4EthereumSentoraPositionManagers.TAKER_POSITION_MANAGER,
        config: AaveV4EthereumSentoraPositionManagers.CONFIG_POSITION_MANAGER,
        nativeGateway: AaveV4EthereumSentoraPositionManagers.NATIVE_TOKEN_GATEWAY,
        signatureGateway: AaveV4EthereumSentoraPositionManagers.SIGNATURE_GATEWAY
      });
  }
}
