// AUTOGENERATED - MANUAL CHANGES WILL BE REVERTED BY THE GENERATOR
// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0;

import {IHub, IHubConfigurator, ISpoke, ISpokeConfigurator, ITokenizationSpoke, ITreasurySpoke, IAaveOracle, IConfigPositionManager, IGiverPositionManager, ITakerPositionManager, INativeTokenGateway, ISignatureGateway, IAaveV4ConfigEngine, IAccessManagerEnumerable, IBasicInterestRateStrategy, PositionManagers} from './AaveV4.sol';
library AaveV4Base {
  // https://basescan.org/address/0x4010C94698EDE9d895814502B6EB122D764a1Cc6
  IAccessManagerEnumerable internal constant ACCESS_MANAGER =
    IAccessManagerEnumerable(0x4010C94698EDE9d895814502B6EB122D764a1Cc6);

  // https://basescan.org/address/0x2Cd40DFF9f2F74e8765dA148102b6668A5e9778A
  IHubConfigurator internal constant HUB_CONFIGURATOR =
    IHubConfigurator(0x2Cd40DFF9f2F74e8765dA148102b6668A5e9778A);

  // https://basescan.org/address/0x0191B1Aa743c6B3C545119B5D56a0577D7f3a57F
  ISpokeConfigurator internal constant SPOKE_CONFIGURATOR =
    ISpokeConfigurator(0x0191B1Aa743c6B3C545119B5D56a0577D7f3a57F);

  // https://basescan.org/address/0x5F8d0102F5B51Fae6DE9d2F2561bda63Fb5Db674
  ITreasurySpoke internal constant TREASURY_SPOKE =
    ITreasurySpoke(0x5F8d0102F5B51Fae6DE9d2F2561bda63Fb5Db674);

  // https://basescan.org/address/0x8753d579B592f3F45902b4Dc13B547B8E8BD03c4
  IAaveV4ConfigEngine internal constant CONFIG_ENGINE =
    IAaveV4ConfigEngine(0x8753d579B592f3F45902b4Dc13B547B8E8BD03c4);

  // https://basescan.org/address/0x577dD4c67d4c7278CdF3bC03aE9a391C4C72DB4f
  address internal constant RISK_STEWARD = 0x577dD4c67d4c7278CdF3bC03aE9a391C4C72DB4f;

  // https://basescan.org/address/0xfbeB4AcB31340bA4de9C87B11dfBf7e2bc8C0bF1
  address internal constant RISK_COUNCIL = 0xfbeB4AcB31340bA4de9C87B11dfBf7e2bc8C0bF1;
}
library AaveV4BaseHubs {
  // https://basescan.org/address/0xa4d5947Eb727A052bae69C593FfC84247EC9864E
  IHub internal constant EQUITIES_HUB = IHub(0xa4d5947Eb727A052bae69C593FfC84247EC9864E);
}
library AaveV4BaseSpokes {
  // https://basescan.org/address/0x5F8d0102F5B51Fae6DE9d2F2561bda63Fb5Db674
  ITreasurySpoke internal constant TREASURY_SPOKE =
    ITreasurySpoke(0x5F8d0102F5B51Fae6DE9d2F2561bda63Fb5Db674);

  // https://basescan.org/address/0x17905Db0e4A3514467539956c084180616AE7B8D
  ISpoke internal constant MAG7_SPOKE = ISpoke(0x17905Db0e4A3514467539956c084180616AE7B8D);

  // https://basescan.org/address/0xaBaf048fD7675Ea34a84332371ffd5D55E322A47
  IAaveOracle internal constant MAG7_SPOKE_ORACLE =
    IAaveOracle(0xaBaf048fD7675Ea34a84332371ffd5D55E322A47);
}
library AaveV4BaseSpokePriceFeeds {
  // https://basescan.org/address/0x787f13dEa48Db0897CbCDD985de77809D837F988
  address internal constant MAG7_SPOKE_AAPLc_PRICE_FEED =
    0x787f13dEa48Db0897CbCDD985de77809D837F988;

  // https://basescan.org/address/0x06A8E4b3aBB3B7543d8396FB2B763d22820cB295
  address internal constant MAG7_SPOKE_AMZNc_PRICE_FEED =
    0x06A8E4b3aBB3B7543d8396FB2B763d22820cB295;

  // https://basescan.org/address/0x5bF49E0ffA937CE2FfF033c739aD7C634c4D34F2
  address internal constant MAG7_SPOKE_GOOGLc_PRICE_FEED =
    0x5bF49E0ffA937CE2FfF033c739aD7C634c4D34F2;

  // https://basescan.org/address/0x6526aE6797A76123638b863AeE4dD27Ba4E4b27D
  address internal constant MAG7_SPOKE_METAc_PRICE_FEED =
    0x6526aE6797A76123638b863AeE4dD27Ba4E4b27D;

  // https://basescan.org/address/0xeB10A6c9aa7E537aEd766C08c35Dae35B321b18c
  address internal constant MAG7_SPOKE_MSFTc_PRICE_FEED =
    0xeB10A6c9aa7E537aEd766C08c35Dae35B321b18c;

  // https://basescan.org/address/0x04689a41629776563E6822F76f2e57D148d28513
  address internal constant MAG7_SPOKE_NVDAc_PRICE_FEED =
    0x04689a41629776563E6822F76f2e57D148d28513;

  // https://basescan.org/address/0xFaf869185383a24F8cb00e27BdA6b63B9905DCb4
  address internal constant MAG7_SPOKE_TSLAc_PRICE_FEED =
    0xFaf869185383a24F8cb00e27BdA6b63B9905DCb4;

  // https://basescan.org/address/0xC7d0f8dCC1F860ca752054c59Ea82Ba2A5AaB50c
  address internal constant MAG7_SPOKE_USDC_PRICE_FEED = 0xC7d0f8dCC1F860ca752054c59Ea82Ba2A5AaB50c;
}
library AaveV4BaseTokenizationSpokes {
  // https://basescan.org/address/0x7081CE7EB1282c53CF38EA9B622f6269cb8FeFDc
  ITokenizationSpoke internal constant EQUITIES_USDC_TOKENIZATION_SPOKE =
    ITokenizationSpoke(0x7081CE7EB1282c53CF38EA9B622f6269cb8FeFDc);
}
library AaveV4BaseIRStrategies {
  // https://basescan.org/address/0x3b0c5FbEff9d32fB6bB706bACc988c88b1871770
  IBasicInterestRateStrategy internal constant EQUITIES_AAPLc_IR_STRATEGY =
    IBasicInterestRateStrategy(0x3b0c5FbEff9d32fB6bB706bACc988c88b1871770);

  // https://basescan.org/address/0x3b0c5FbEff9d32fB6bB706bACc988c88b1871770
  IBasicInterestRateStrategy internal constant EQUITIES_AMZNc_IR_STRATEGY =
    IBasicInterestRateStrategy(0x3b0c5FbEff9d32fB6bB706bACc988c88b1871770);

  // https://basescan.org/address/0x3b0c5FbEff9d32fB6bB706bACc988c88b1871770
  IBasicInterestRateStrategy internal constant EQUITIES_GOOGLc_IR_STRATEGY =
    IBasicInterestRateStrategy(0x3b0c5FbEff9d32fB6bB706bACc988c88b1871770);

  // https://basescan.org/address/0x3b0c5FbEff9d32fB6bB706bACc988c88b1871770
  IBasicInterestRateStrategy internal constant EQUITIES_METAc_IR_STRATEGY =
    IBasicInterestRateStrategy(0x3b0c5FbEff9d32fB6bB706bACc988c88b1871770);

  // https://basescan.org/address/0x3b0c5FbEff9d32fB6bB706bACc988c88b1871770
  IBasicInterestRateStrategy internal constant EQUITIES_MSFTc_IR_STRATEGY =
    IBasicInterestRateStrategy(0x3b0c5FbEff9d32fB6bB706bACc988c88b1871770);

  // https://basescan.org/address/0x3b0c5FbEff9d32fB6bB706bACc988c88b1871770
  IBasicInterestRateStrategy internal constant EQUITIES_NVDAc_IR_STRATEGY =
    IBasicInterestRateStrategy(0x3b0c5FbEff9d32fB6bB706bACc988c88b1871770);

  // https://basescan.org/address/0x3b0c5FbEff9d32fB6bB706bACc988c88b1871770
  IBasicInterestRateStrategy internal constant EQUITIES_TSLAc_IR_STRATEGY =
    IBasicInterestRateStrategy(0x3b0c5FbEff9d32fB6bB706bACc988c88b1871770);

  // https://basescan.org/address/0x3b0c5FbEff9d32fB6bB706bACc988c88b1871770
  IBasicInterestRateStrategy internal constant EQUITIES_USDC_IR_STRATEGY =
    IBasicInterestRateStrategy(0x3b0c5FbEff9d32fB6bB706bACc988c88b1871770);
}
library AaveV4BasePositionManagers {
  // https://basescan.org/address/0x9E81c2fDE4E34CAB3AB1667ca3c932dBAED95F08
  IGiverPositionManager internal constant GIVER_POSITION_MANAGER =
    IGiverPositionManager(0x9E81c2fDE4E34CAB3AB1667ca3c932dBAED95F08);

  // https://basescan.org/address/0x8481204E528735aF2F3391AD98f36E757A56D695
  ITakerPositionManager internal constant TAKER_POSITION_MANAGER =
    ITakerPositionManager(0x8481204E528735aF2F3391AD98f36E757A56D695);

  // https://basescan.org/address/0xe90F830bEe4b190B4910e146908437075b0BDaaF
  IConfigPositionManager internal constant CONFIG_POSITION_MANAGER =
    IConfigPositionManager(0xe90F830bEe4b190B4910e146908437075b0BDaaF);

  // https://basescan.org/address/0xdFC11f7037Ba11D9cC29A822844f5dC19C42B70d
  INativeTokenGateway internal constant NATIVE_TOKEN_GATEWAY =
    INativeTokenGateway(0xdFC11f7037Ba11D9cC29A822844f5dC19C42B70d);

  // https://basescan.org/address/0x5d488d3EAAa86DDb6D4f834FC34938054eC505A7
  ISignatureGateway internal constant SIGNATURE_GATEWAY =
    ISignatureGateway(0x5d488d3EAAa86DDb6D4f834FC34938054eC505A7);
}
library AaveV4BaseExternalLibraries {
  // https://basescan.org/address/0x88dF535473C5adf1f57789734A05E555F7Deb8DB
  address internal constant LIQUIDATION_LOGIC = 0x88dF535473C5adf1f57789734A05E555F7Deb8DB;
}
library AaveV4BaseAssets {
  // https://basescan.org/address/0xb200000000000000000000C2e324d24d7eEcd1fb
  address internal constant AAPLc_UNDERLYING = 0xb200000000000000000000C2e324d24d7eEcd1fb;

  uint8 internal constant AAPLc_DECIMALS = 8;

  // https://basescan.org/address/0xb200000000000000000000d9192b6B456483C2E8
  address internal constant AMZNc_UNDERLYING = 0xb200000000000000000000d9192b6B456483C2E8;

  uint8 internal constant AMZNc_DECIMALS = 8;

  // https://basescan.org/address/0xb2000000000000000000002D0BA3164cc74f58B7
  address internal constant GOOGLc_UNDERLYING = 0xb2000000000000000000002D0BA3164cc74f58B7;

  uint8 internal constant GOOGLc_DECIMALS = 8;

  // https://basescan.org/address/0xb2000000000000000000008bC8786B856E61707C
  address internal constant METAc_UNDERLYING = 0xb2000000000000000000008bC8786B856E61707C;

  uint8 internal constant METAc_DECIMALS = 8;

  // https://basescan.org/address/0xB200000000000000000000Ab99cFa739E253872B
  address internal constant MSFTc_UNDERLYING = 0xB200000000000000000000Ab99cFa739E253872B;

  uint8 internal constant MSFTc_DECIMALS = 8;

  // https://basescan.org/address/0xb20000000000000000000078ee7ce2fE4908108C
  address internal constant NVDAc_UNDERLYING = 0xb20000000000000000000078ee7ce2fE4908108C;

  uint8 internal constant NVDAc_DECIMALS = 8;

  // https://basescan.org/address/0xb2000000000000000000001e800a7f5189430cD0
  address internal constant TSLAc_UNDERLYING = 0xb2000000000000000000001e800a7f5189430cD0;

  uint8 internal constant TSLAc_DECIMALS = 8;

  // https://basescan.org/address/0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913
  address internal constant USDC_UNDERLYING = 0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913;

  uint8 internal constant USDC_DECIMALS = 6;
}
library AaveV4BaseGetters {
  function getAllHubs() internal pure returns (IHub[] memory) {
    IHub[] memory hubs = new IHub[](1);
    hubs[0] = AaveV4BaseHubs.EQUITIES_HUB;
    return hubs;
  }

  function getAllSpokes() internal pure returns (ISpoke[] memory) {
    ISpoke[] memory spokes = new ISpoke[](1);
    spokes[0] = AaveV4BaseSpokes.MAG7_SPOKE;
    return spokes;
  }

  function getAllTokenizationSpokes() internal pure returns (ITokenizationSpoke[] memory) {
    ITokenizationSpoke[] memory tokenizedSpokes = new ITokenizationSpoke[](1);
    tokenizedSpokes[0] = AaveV4BaseTokenizationSpokes.EQUITIES_USDC_TOKENIZATION_SPOKE;
    return tokenizedSpokes;
  }

  function getAllSpokesRaw() internal pure returns (address[] memory) {
    address[] memory spokes = new address[](3);
    spokes[0] = address(AaveV4BaseSpokes.TREASURY_SPOKE);
    spokes[1] = address(AaveV4BaseSpokes.MAG7_SPOKE);
    spokes[2] = address(AaveV4BaseTokenizationSpokes.EQUITIES_USDC_TOKENIZATION_SPOKE);
    return spokes;
  }

  function getPositionManagers() internal pure returns (PositionManagers memory) {
    return
      PositionManagers({
        giver: AaveV4BasePositionManagers.GIVER_POSITION_MANAGER,
        taker: AaveV4BasePositionManagers.TAKER_POSITION_MANAGER,
        config: AaveV4BasePositionManagers.CONFIG_POSITION_MANAGER,
        nativeGateway: AaveV4BasePositionManagers.NATIVE_TOKEN_GATEWAY,
        signatureGateway: AaveV4BasePositionManagers.SIGNATURE_GATEWAY
      });
  }
}
