// AUTOGENERATED - MANUAL CHANGES WILL BE REVERTED BY THE GENERATOR
// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0;

library GhoArbitrum {
  // https://arbiscan.io/address/0x7dfF72693f6A4149b17e7C6314655f6A9F7c8B33
  address internal constant GHO_TOKEN = 0x7dfF72693f6A4149b17e7C6314655f6A9F7c8B33;

  // https://arbiscan.io/address/0xB94Ab28c6869466a46a42abA834ca2B3cECCA5eB
  address internal constant GHO_CCIP_TOKEN_POOL = 0xB94Ab28c6869466a46a42abA834ca2B3cECCA5eB;

  // https://arbiscan.io/address/0x812fBcd390A3C6c01C65B767413Dea6f6e24FDD0
  address internal constant GHO_CCIP_BRIDGE = 0x812fBcd390A3C6c01C65B767413Dea6f6e24FDD0;

  // https://arbiscan.io/address/0xa9afaE6A53E90f9E4CE0717162DF5Bc3d9aBe7B2
  address internal constant GHO_BUCKET_STEWARD = 0xa9afaE6A53E90f9E4CE0717162DF5Bc3d9aBe7B2;

  // https://arbiscan.io/address/0xCd5ab470AaC5c13e1063ee700503f3346b7C90Db
  address internal constant GHO_CCIP_STEWARD = 0xCd5ab470AaC5c13e1063ee700503f3346b7C90Db;

  // https://arbiscan.io/address/0x4DFfA29C526b5CFB419e14E3111516Fbf929797D
  address internal constant GHO_GSM_STEWARD = 0x4DFfA29C526b5CFB419e14E3111516Fbf929797D;

  // https://arbiscan.io/address/0xd2D586f849620ef042FE3aF52eAa10e9b78bf7De
  address internal constant GHO_AAVE_CORE_STEWARD = 0xd2D586f849620ef042FE3aF52eAa10e9b78bf7De;

  // https://arbiscan.io/address/0xC912D64F9F649897dC0244da3835869d410d053e
  address internal constant GHO_RESERVE = 0xC912D64F9F649897dC0244da3835869d410d053e;

  // https://arbiscan.io/address/0x1aEe7A618B0CC687cCED9aB796e464062f1508CA
  address internal constant GSM_USDCn = 0x1aEe7A618B0CC687cCED9aB796e464062f1508CA;

  // https://arbiscan.io/address/0x2169Bf2084bDb881587b3Cf6B24011E6AA091FdE
  address internal constant GSM_USDCn_FEE_STRATEGY = 0x2169Bf2084bDb881587b3Cf6B24011E6AA091FdE;

  // https://arbiscan.io/address/0x4daF7FCe9EfcA48e9274b35b5A7B4639b0DdFCCa
  address internal constant GSM_USDCn_ORACLE_SWAP_FREEZER =
    0x4daF7FCe9EfcA48e9274b35b5A7B4639b0DdFCCa;

  // https://arbiscan.io/address/0x8513e6F37dBc52De87b166980Fa3F50639694B60
  address internal constant RISK_COUNCIL = 0x8513e6F37dBc52De87b166980Fa3F50639694B60;

  // https://arbiscan.io/address/0x2Be58aD215AA8552CB5BD038a88d0dE39d2427BB
  address internal constant GSM_REGISTRY = 0x2Be58aD215AA8552CB5BD038a88d0dE39d2427BB;

  // https://arbiscan.io/address/0xF5F579926e704C01Bb6e51e18751F5E2b17B0cCC
  address internal constant FEE_STRATEGY_FACTORY = 0xF5F579926e704C01Bb6e51e18751F5E2b17B0cCC;
}
